### orientational averaging

In [76]:
import macroscopics
import mtRspfuncs
import numpy as np
np.set_printoptions(linewidth=100000)

polarizations =  [[0.0, 0.0, 1.0], [0.0, 0.0, 1.0], [0.0, 0.0, 1.0], [0.0, 0.0, 1.0]]
num_fields = 4

# polarizations =  [[0.0, 0.0, 1.0], [0.0, 0.0, 1.0], [0.0, 0.0, 1.0]]
# num_fields = 3

pol_laser = macroscopics.get_pol_laser(polarizations)
pol_mat = macroscopics.get_iso_mat(num_fields)
pol_g = macroscopics.get_iso_f(num_fields)

print(pol_laser)
print(pol_mat)
print(np.array(pol_g, dtype='object'))

# print('-----------------------')
# polarizations =  [[0.0, 0.0, 1.0], [0.0, 0.0, 1.0], [0.0, 0.0, 1.0], [0.0, 0.0, 1.0]]
# num_fields = 3

# pol_laser = macroscopics.get_pol_laser(polarizations)
# pol_mat = macroscopics.get_iso_mat(num_fields)
# pol_g = macroscopics.get_iso_f(num_fields)

# print(pol_laser)
# print(pol_mat)
# print(np.array(pol_g, dtype='object'))

[1. 1. 1.]
[[ 0.13333333 -0.03333333 -0.03333333]
 [-0.03333333  0.13333333 -0.03333333]
 [-0.03333333 -0.03333333  0.13333333]]
[[list([[0, 0, 0, 0], [0, 0, 1, 1], [0, 0, 2, 2], [1, 1, 0, 0], [1, 1, 1, 1], [1, 1, 2, 2], [2, 2, 0, 0], [2, 2, 1, 1], [2, 2, 2, 2]]) list([])]
 [list([[0, 0, 0, 0], [0, 1, 0, 1], [0, 2, 0, 2], [1, 0, 1, 0], [1, 1, 1, 1], [1, 2, 1, 2], [2, 0, 2, 0], [2, 1, 2, 1], [2, 2, 2, 2]]) list([])]
 [list([[0, 0, 0, 0], [0, 1, 1, 0], [0, 2, 2, 0], [1, 0, 0, 1], [1, 1, 1, 1], [1, 2, 2, 1], [2, 0, 0, 2], [2, 1, 1, 2], [2, 2, 2, 2]]) list([])]]
-----------------------
[1. 1. 1.]
1.0
[[list([(0, 1, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0), (1, 0, 2), (0, 2, 1)]) list([])]]


In [75]:
p = np.array([['Saa*S_bb'], ['Sab*S_ab'], ['Sab*S_ba']], dtype=object)
p = np.array([2, 3, 4], dtype=object)

m = np.array([[4, -1, -1], [-1, 4, -1], [-1, -1, 4]], dtype=object)/30
Af = np.array([1, 1, 1]).T

xx = np.inner(Af, m)
print(xxx)
xxx = np.inner(xx, p)
print(xxx)

q = np.outer(m, p)
# print(q)

18
0.6000000000000001


In [52]:
z = np.array([0., 0., 1.])
np.outer(z, z)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [59]:
zz = np.einsum('i,j', z, z)
zzzz = np.einsum('ij,kl', zz, zz)
# print(zz)
print(zzzz)

[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 1.]]]]


In [55]:
zz = np.outer(z, z)
zzz = np.outer(zz, z)
zzzz = np.outer(zzz, z)

print(zz)
# print(zzz)
print(zzzz)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]


In [26]:
x = np.array(['a', 'b', 'c'], dtype=object)
np.outer(x, [1, 2, 3])

array([['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']], dtype=object)

In [28]:
a = np.arange(25).reshape(5,5)
b = np.arange(5)
c = np.arange(6).reshape(2,3)

In [30]:
np.einsum('ii', a)
np.trace(a)

60

In [32]:
print(a)
print(b)

np.einsum('i,j', np.arange(2)+1, b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[0 1 2 3 4]


array([[0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])