In [16]:
import numpy as np

x = np.arange(30)

# x.shape = (2, 15)
# print(x)
# print(x[1, 3])

x.shape = (2, 3, 5)
print(x)
print(x[1, 2, 3])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
28


In [18]:
print(x[:, :, 0])

[[ 0  5 10]
 [15 20 25]]


In [22]:
print(len(x))
print(len(x[0]))
print(len(x[0, 0]))

2
3
5


In [7]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rows = np.array([[0, 0],
                 [3, 3]], dtype=np.intp)
columns = np.array([[0, 2],
                    [0, 2]], dtype=np.intp)
x[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

In [27]:
import functools

def function_call_counter(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        wrapper.count += 1
        # print(f"-----> Function '{func.__name__}' called {wrapper.count} times.")
        print(f"-----> #{wrapper.count} - function '{func.__name__}' call")
        print(f"-----> Arguments: {args}, {kwargs}")
        return func(*args, **kwargs)
    
    wrapper.count = 0
    return wrapper

def my_function(arg1, arg2):
    # Function implementation goes here
    print('hii '+arg1)
    pass

def another_function():
    # Function implementation goes here
    print('hello')
    pass


# Wrap the functions with the function_call_counter wrapper
my_function = function_call_counter(my_function)
another_function = function_call_counter(another_function)

# Call the functions as usual
my_function("Hello", arg2=42)
my_function("World", arg2=24)
another_function()

-----> #1 - function 'my_function' call
-----> Arguments: ('Hello',), {'arg2': 42}
hii Hello
-----> #2 - function 'my_function' call
-----> Arguments: ('World',), {'arg2': 24}
hii World
-----> #1 - function 'another_function' call
-----> Arguments: (), {}
hello


In [28]:
def factorial(x):
    """This is a recursive function
    to find the factorial of an integer"""

    if x == 1:
        return 1
    else:
        return (x * factorial(x-1))


# num = 3
# print("The factorial of", num, "is", factorial(num))
factorial = function_call_counter(factorial)
factorial(5)



-----> #1 - function 'factorial' call
-----> Arguments: (5,), {}
-----> #2 - function 'factorial' call
-----> Arguments: (4,), {}
-----> #3 - function 'factorial' call
-----> Arguments: (3,), {}
-----> #4 - function 'factorial' call
-----> Arguments: (2,), {}
-----> #5 - function 'factorial' call
-----> Arguments: (1,), {}


120

In [32]:
import numpy as np

# Assuming you have a function `my_function` that acts on meshgrid X and Y
def my_function(X, Y):
    # ... function implementation ...
    return X+Y

# Define the desired values of x and y
desired_x = 2.5
desired_y = 1.0

# Create the meshgrid
x = np.linspace(0, 5, 11)
y = np.linspace(0, 2, 5)
X, Y = np.meshgrid(x, y)

# Call your function with the meshgrid
result = my_function(X, Y)

# Find the indices that correspond to the desired values of x and y
x_index = np.where(x == desired_x)[0][0]
y_index = np.where(y == desired_y)[0][0]

# Access the corresponding element in the result matrix
desired_element = result[y_index, x_index]

# Print the desired element
print(desired_element)
print(result)
print(x, y)

3.5
[[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
 [0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]
 [1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6. ]
 [1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5]
 [2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7. ]]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ] [0.  0.5 1.  1.5 2. ]


In [33]:
a = np.arange(25).reshape(5,5)
b = np.arange(5)
c = np.arange(6).reshape(2,3)

In [39]:
a = np.arange(24.).reshape(2,3,4)
b = np.arange(12.).reshape(2,3,2)
# np.einsum('ijk,jil->kl', a, b)
print(a)
print('-----')
print(b)
np.einsum('')

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
-----
[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]]

 [[ 6.  7.]
  [ 8.  9.]
  [10. 11.]]]


ValueError: must specify the einstein sum subscripts string and at least one operand

In [41]:
'ijkl'[:3]

'ijk'

In [44]:
'ijkl'[0]

'i'